import type { Article } from '../lib/types';
import indexJson from '../generated/articles-index.json';

/**
 * SLIM article index — what every landing page should import.
 *
 * `./articles` eagerly globs all 25 FULL articles (478 KB, of which `body` is 71%
 * and `faqs` 16%). The seven landing pages only ever render a card — title,
 * shortIntro, heroImage, publishDate — so importing the full module from them put
 * a 119 KB-gzipped chunk on every page in the site. Full bodies are read by one
 * consumer, `pages/articles/Detail.tsx`, which is now a lazy route.
 *
 * Generated by `scripts/content-index-gen.mjs` (runs at the head of `npm run build`).
 */
export type ArticleListItem = Pick<
  Article,
  | 'slug'
  | 'category'
  | 'title'
  | 'shortIntro'
  | 'heroImage'
  | 'publishDate'
  | 'relatedSlugs'
  | 'metaDescription'
  | 'primaryKeyword'
>;

export const articleList = indexJson as ArticleListItem[];

export const articleListByCategory = (cat: Article['category']): ArticleListItem[] =>
  articleList.filter((a) => a.category === cat);

/** Kept identical to the one in ./articles so no link on the site changes shape. */
export const articlePath = (a: Pick<Article, 'category' | 'slug'>): string => {
  const map: Record<Article['category'], string> = {
    simhastha: '/simhastha-2028',
    transport: '/transport-in-ujjain',
    tour: '/tour-and-travel-ujjain',
    'puja-info': '/puja-in-ujjain',
    blog: '/blog',
  };
  return `${map[a.category]}/${a.slug}/`;
};
