import type { Mandir } from '../lib/types';
import indexJson from '../generated/mandirs-index.json';

/**
 * SLIM mandir index — the only mandir data that list/card surfaces should import.
 *
 * `./mandirs` eagerly globs all 183 FULL records (1.4 MB of JSON: history,
 * weeklyTiming, faqs, howToReach…). Importing it from the home page, /mandirs/,
 * things-to-do or the route table dragged that whole payload into a `content`
 * chunk that was `modulepreload`ed on EVERY page — 395 KB gzipped, on a site whose
 * copy is already baked into the SSG HTML. This index carries the ~15% those
 * surfaces actually read, and `./mandirs` is now imported by the lazily-loaded
 * temple Detail route alone.
 *
 * Generated by `scripts/content-index-gen.mjs`, which runs at the head of
 * `npm run build`. Need another field on a card? Add it to LIST_FIELDS there —
 * and remember it costs bytes on every page.
 */
export type MandirListItem = Pick<
  Mandir,
  | 'slug'
  | 'name'
  | 'shortIntro'
  | 'photos'
  | 'isFeatured'
  | 'templeType'
  | 'nearbyMandirs'
  | 'deity'
  | 'locationArea'
  | 'darshanTimingSummary'
>;

/** Pre-sorted by the generator: Mahakaleshwar first, then featured, then A-Z (en). */
export const mandirList = indexJson as MandirListItem[];

export const mandirListBySlug = new Map(mandirList.map((m) => [m.slug, m]));

export const featuredMandirList = mandirList.filter((m) => m.isFeatured);
